// Generated by scripts/generateNorthstarMockData.mjs.
// Do not edit by hand; update the generator and rerun it.

export const generatedWorkOrders = [
  {
    "id": "WO-GAS-1001",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Needs assignment",
    "district": "North",
    "sla": "35 min remaining",
    "impact": "120 customers affected",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.67865,
    "latitude": 45.5605
  },
  {
    "id": "WO-GAS-1002",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Queued",
    "district": "Central",
    "sla": "7 hr",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6643,
    "latitude": 45.51615
  },
  {
    "id": "WO-GAS-1003",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Scheduled",
    "district": "South",
    "sla": "3 days",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.64895,
    "latitude": 45.4998
  },
  {
    "id": "WO-GAS-1004",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "North",
    "sla": "38 min remaining",
    "impact": "Gas field operation in North district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6726,
    "latitude": 45.56545
  },
  {
    "id": "WO-GAS-1005",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "1 hr 14 min",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.65825,
    "latitude": 45.5211
  },
  {
    "id": "WO-GAS-1006",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Needs assignment",
    "district": "South",
    "sla": "11 hr",
    "impact": "275 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6429,
    "latitude": 45.50475
  },
  {
    "id": "WO-GAS-1007",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Queued",
    "district": "North",
    "sla": "2 days",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.66655,
    "latitude": 45.5704
  },
  {
    "id": "WO-GAS-1008",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "Central",
    "sla": "42 min remaining",
    "impact": "Gas field operation in Central district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6522,
    "latitude": 45.52605
  },
  {
    "id": "WO-GAS-1009",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Assigned",
    "district": "South",
    "sla": "1 hr 18 min",
    "impact": "Gas field operation in South district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.69185,
    "latitude": 45.5097
  },
  {
    "id": "WO-GAS-1010",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Ready to bundle",
    "district": "North",
    "sla": "15 hr",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6605,
    "latitude": 45.57535
  },
  {
    "id": "WO-GAS-1011",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Needs assignment",
    "district": "Central",
    "sla": "1 days",
    "impact": "430 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.64615,
    "latitude": 45.531
  },
  {
    "id": "WO-GAS-1012",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Queued",
    "district": "South",
    "sla": "46 min remaining",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6858,
    "latitude": 45.46965
  },
  {
    "id": "WO-GAS-1013",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Scheduled",
    "district": "North",
    "sla": "1 hr 22 min",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.65445,
    "latitude": 45.5803
  },
  {
    "id": "WO-GAS-1014",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Assigned",
    "district": "Central",
    "sla": "7 hr",
    "impact": "Gas field operation in Central district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6401,
    "latitude": 45.53595
  },
  {
    "id": "WO-GAS-1015",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Ready to bundle",
    "district": "South",
    "sla": "5 days",
    "impact": "Gas field operation in South district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.67975,
    "latitude": 45.4746
  },
  {
    "id": "WO-GAS-1016",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Needs assignment",
    "district": "North",
    "sla": "50 min remaining",
    "impact": "585 customers affected",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6484,
    "latitude": 45.58525
  },
  {
    "id": "WO-GAS-1017",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Queued",
    "district": "Central",
    "sla": "1 hr 26 min",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.63405,
    "latitude": 45.5409
  },
  {
    "id": "WO-GAS-1018",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Scheduled",
    "district": "South",
    "sla": "11 hr",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6737,
    "latitude": 45.47955
  },
  {
    "id": "WO-GAS-1019",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Assigned",
    "district": "North",
    "sla": "4 days",
    "impact": "Gas field operation in North district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.64235,
    "latitude": 45.5902
  },
  {
    "id": "WO-GAS-1020",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "54 min remaining",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.683,
    "latitude": 45.50085
  },
  {
    "id": "WO-GAS-1021",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Needs assignment",
    "district": "South",
    "sla": "1 hr 30 min",
    "impact": "740 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.66765,
    "latitude": 45.4845
  },
  {
    "id": "WO-GAS-1022",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Queued",
    "district": "North",
    "sla": "15 hr",
    "impact": "Gas field operation in North district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6363,
    "latitude": 45.59515
  },
  {
    "id": "WO-GAS-1023",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "Central",
    "sla": "57 min remaining",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.67695,
    "latitude": 45.5058
  },
  {
    "id": "WO-GAS-1024",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "South",
    "sla": "58 min remaining",
    "impact": "Gas field operation in South district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6616,
    "latitude": 45.48945
  },
  {
    "id": "WO-GAS-1025",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Ready to bundle",
    "district": "North",
    "sla": "1 hr 34 min",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.63025,
    "latitude": 45.6001
  },
  {
    "id": "WO-GAS-1026",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Needs assignment",
    "district": "Central",
    "sla": "7 hr",
    "impact": "895 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6709,
    "latitude": 45.51075
  },
  {
    "id": "WO-GAS-1027",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Queued",
    "district": "South",
    "sla": "2 days",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.65555,
    "latitude": 45.4944
  },
  {
    "id": "WO-GAS-1028",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "North",
    "sla": "62 min remaining",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6792,
    "latitude": 45.60505
  },
  {
    "id": "WO-GAS-1029",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Assigned",
    "district": "Central",
    "sla": "1 hr 38 min",
    "impact": "Gas field operation in Central district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.66485,
    "latitude": 45.5157
  },
  {
    "id": "WO-GAS-1030",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Ready to bundle",
    "district": "South",
    "sla": "11 hr",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6495,
    "latitude": 45.49935
  },
  {
    "id": "WO-GAS-1031",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Needs assignment",
    "district": "North",
    "sla": "1 days",
    "impact": "150 customers affected",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.67315,
    "latitude": 45.565
  },
  {
    "id": "WO-GAS-1032",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Queued",
    "district": "Central",
    "sla": "66 min remaining",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6588,
    "latitude": 45.52065
  },
  {
    "id": "WO-GAS-1033",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Scheduled",
    "district": "South",
    "sla": "1 hr 42 min",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.64345,
    "latitude": 45.5043
  },
  {
    "id": "WO-GAS-1034",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "North",
    "sla": "68 min remaining",
    "impact": "Gas field operation in North district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6671,
    "latitude": 45.56995
  },
  {
    "id": "WO-GAS-1035",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "5 days",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.65275,
    "latitude": 45.5256
  },
  {
    "id": "WO-GAS-1036",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Needs assignment",
    "district": "South",
    "sla": "70 min remaining",
    "impact": "305 customers affected",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6924,
    "latitude": 45.50925
  },
  {
    "id": "WO-GAS-1037",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Queued",
    "district": "North",
    "sla": "1 hr 46 min",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.66105,
    "latitude": 45.5749
  },
  {
    "id": "WO-GAS-1038",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Scheduled",
    "district": "Central",
    "sla": "7 hr",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6467,
    "latitude": 45.53055
  },
  {
    "id": "WO-GAS-1039",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Assigned",
    "district": "South",
    "sla": "4 days",
    "impact": "Gas field operation in South district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.68635,
    "latitude": 45.4692
  },
  {
    "id": "WO-GAS-1040",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Ready to bundle",
    "district": "North",
    "sla": "74 min remaining",
    "impact": "Gas field operation in North district",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.655,
    "latitude": 45.57985
  },
  {
    "id": "WO-GAS-1041",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Needs assignment",
    "district": "Central",
    "sla": "1 hr 50 min",
    "impact": "460 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.64065,
    "latitude": 45.5355
  },
  {
    "id": "WO-GAS-1042",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Queued",
    "district": "South",
    "sla": "11 hr",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6803,
    "latitude": 45.47415
  },
  {
    "id": "WO-GAS-1043",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Scheduled",
    "district": "North",
    "sla": "3 days",
    "impact": "Gas field operation in North district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.64895,
    "latitude": 45.5848
  },
  {
    "id": "WO-GAS-1044",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "Central",
    "sla": "78 min remaining",
    "impact": "Gas field operation in Central district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6346,
    "latitude": 45.54045
  },
  {
    "id": "WO-GAS-1045",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Ready to bundle",
    "district": "South",
    "sla": "79 min remaining",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.67425,
    "latitude": 45.4791
  },
  {
    "id": "WO-GAS-1046",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Needs assignment",
    "district": "North",
    "sla": "15 hr",
    "impact": "615 customers affected",
    "crew": "Gas crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6429,
    "latitude": 45.58975
  },
  {
    "id": "WO-GAS-1047",
    "type": "Regulator Maintenance",
    "domain": "Gas",
    "priority": "Routine",
    "status": "Queued",
    "district": "Central",
    "sla": "2 days",
    "impact": "Gas field operation in Central district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Pressure regulation",
      "Compliance photos"
    ],
    "equipment": [
      "Pressure kit",
      "Service truck"
    ],
    "longitude": -122.68355,
    "latitude": 45.5004
  },
  {
    "id": "WO-GAS-1048",
    "type": "Corrosion Inspection",
    "domain": "Gas",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "South",
    "sla": "82 min remaining",
    "impact": "Gas field operation in South district",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Corrosion inspection",
      "Compliance photos"
    ],
    "equipment": [
      "Inspection van",
      "Survey kit"
    ],
    "longitude": -122.6682,
    "latitude": 45.48405
  },
  {
    "id": "WO-GAS-1049",
    "type": "Gas Leak Investigation",
    "domain": "Gas",
    "priority": "Critical",
    "status": "Assigned",
    "district": "North",
    "sla": "1 hr 13 min",
    "impact": "Gas field operation in North district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas emergency",
      "Atmospheric testing",
      "Vacuum excavation"
    ],
    "equipment": [
      "Leak detector",
      "Vac truck",
      "Traffic kit"
    ],
    "longitude": -122.63685,
    "latitude": 45.5947
  },
  {
    "id": "WO-GAS-1050",
    "type": "Gas Service Installation",
    "domain": "Gas",
    "priority": "High",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "7 hr",
    "impact": "Gas field operation in Central district",
    "crew": "Gas assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Gas service",
      "Excavation",
      "Customer relight"
    ],
    "equipment": [
      "Service truck",
      "Fusion kit",
      "Traffic kit"
    ],
    "longitude": -122.6775,
    "latitude": 45.50535
  },
  {
    "id": "WO-ELEC-2001",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Needs assignment",
    "district": "North",
    "sla": "35 min remaining",
    "impact": "35 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.70765,
    "latitude": 45.5605
  },
  {
    "id": "WO-ELEC-2002",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Queued",
    "district": "Central",
    "sla": "2 days",
    "impact": "82 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.6873,
    "latitude": 45.52515
  },
  {
    "id": "WO-ELEC-2003",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "West",
    "sla": "37 min remaining",
    "impact": "129 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.76395,
    "latitude": 45.5268
  },
  {
    "id": "WO-ELEC-2004",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Assigned",
    "district": "North",
    "sla": "4 hr 13 min",
    "impact": "176 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.7016,
    "latitude": 45.56545
  },
  {
    "id": "WO-ELEC-2005",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "High",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "10 hr",
    "impact": "223 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.68125,
    "latitude": 45.5301
  },
  {
    "id": "WO-ELEC-2006",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Needs assignment",
    "district": "West",
    "sla": "1 days",
    "impact": "270 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.7579,
    "latitude": 45.53175
  },
  {
    "id": "WO-ELEC-2007",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Queued",
    "district": "North",
    "sla": "41 min remaining",
    "impact": "317 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.69555,
    "latitude": 45.5704
  },
  {
    "id": "WO-ELEC-2008",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Scheduled",
    "district": "Central",
    "sla": "4 hr 17 min",
    "impact": "364 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.6752,
    "latitude": 45.53505
  },
  {
    "id": "WO-ELEC-2009",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "High",
    "status": "Assigned",
    "district": "West",
    "sla": "14 hr",
    "impact": "411 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.80685,
    "latitude": 45.5367
  },
  {
    "id": "WO-ELEC-2010",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Ready to bundle",
    "district": "North",
    "sla": "5 days",
    "impact": "458 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.6895,
    "latitude": 45.57535
  },
  {
    "id": "WO-ELEC-2011",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Needs assignment",
    "district": "Central",
    "sla": "45 min remaining",
    "impact": "505 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.66915,
    "latitude": 45.54
  },
  {
    "id": "WO-ELEC-2012",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Queued",
    "district": "West",
    "sla": "46 min remaining",
    "impact": "552 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.8008,
    "latitude": 45.49665
  },
  {
    "id": "WO-ELEC-2013",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "High",
    "status": "Scheduled",
    "district": "North",
    "sla": "6 hr",
    "impact": "599 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.68345,
    "latitude": 45.5803
  },
  {
    "id": "WO-ELEC-2014",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Assigned",
    "district": "Central",
    "sla": "4 days",
    "impact": "646 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.6631,
    "latitude": 45.54495
  },
  {
    "id": "WO-ELEC-2015",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Ready to bundle",
    "district": "West",
    "sla": "49 min remaining",
    "impact": "693 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.79475,
    "latitude": 45.5016
  },
  {
    "id": "WO-ELEC-2016",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Needs assignment",
    "district": "North",
    "sla": "4 hr 25 min",
    "impact": "740 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.6774,
    "latitude": 45.58525
  },
  {
    "id": "WO-ELEC-2017",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "High",
    "status": "Queued",
    "district": "Central",
    "sla": "10 hr",
    "impact": "787 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.65705,
    "latitude": 45.5499
  },
  {
    "id": "WO-ELEC-2018",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Scheduled",
    "district": "West",
    "sla": "3 days",
    "impact": "834 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.7887,
    "latitude": 45.50655
  },
  {
    "id": "WO-ELEC-2019",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "North",
    "sla": "53 min remaining",
    "impact": "881 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.67135,
    "latitude": 45.5902
  },
  {
    "id": "WO-ELEC-2020",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "4 hr 29 min",
    "impact": "928 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.706,
    "latitude": 45.50985
  },
  {
    "id": "WO-ELEC-2021",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "High",
    "status": "Needs assignment",
    "district": "West",
    "sla": "14 hr",
    "impact": "975 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.78265,
    "latitude": 45.5115
  },
  {
    "id": "WO-ELEC-2022",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Queued",
    "district": "North",
    "sla": "2 days",
    "impact": "1,022 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.6653,
    "latitude": 45.59515
  },
  {
    "id": "WO-ELEC-2023",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "Central",
    "sla": "57 min remaining",
    "impact": "1,069 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.69995,
    "latitude": 45.5148
  },
  {
    "id": "WO-ELEC-2024",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Assigned",
    "district": "West",
    "sla": "4 hr 33 min",
    "impact": "1,116 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.7766,
    "latitude": 45.51645
  },
  {
    "id": "WO-ELEC-2025",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "High",
    "status": "Ready to bundle",
    "district": "North",
    "sla": "6 hr",
    "impact": "1,163 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.65925,
    "latitude": 45.6001
  },
  {
    "id": "WO-ELEC-2026",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Needs assignment",
    "district": "Central",
    "sla": "1 days",
    "impact": "1,210 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.6939,
    "latitude": 45.51975
  },
  {
    "id": "WO-ELEC-2027",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Queued",
    "district": "West",
    "sla": "61 min remaining",
    "impact": "1,257 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.77055,
    "latitude": 45.5214
  },
  {
    "id": "WO-ELEC-2028",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Scheduled",
    "district": "North",
    "sla": "4 hr 37 min",
    "impact": "1,304 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.7082,
    "latitude": 45.60505
  },
  {
    "id": "WO-ELEC-2029",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "High",
    "status": "Assigned",
    "district": "Central",
    "sla": "10 hr",
    "impact": "1,351 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.68785,
    "latitude": 45.5247
  },
  {
    "id": "WO-ELEC-2030",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Ready to bundle",
    "district": "West",
    "sla": "5 days",
    "impact": "1,398 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.7645,
    "latitude": 45.52635
  },
  {
    "id": "WO-ELEC-2031",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Needs assignment",
    "district": "North",
    "sla": "65 min remaining",
    "impact": "1,445 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.70215,
    "latitude": 45.565
  },
  {
    "id": "WO-ELEC-2032",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Queued",
    "district": "Central",
    "sla": "4 hr 41 min",
    "impact": "1,492 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.6818,
    "latitude": 45.52965
  },
  {
    "id": "WO-ELEC-2033",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "High",
    "status": "Scheduled",
    "district": "West",
    "sla": "14 hr",
    "impact": "1,539 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.75845,
    "latitude": 45.5313
  },
  {
    "id": "WO-ELEC-2034",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "North",
    "sla": "68 min remaining",
    "impact": "1,586 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.6961,
    "latitude": 45.56995
  },
  {
    "id": "WO-ELEC-2035",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "69 min remaining",
    "impact": "1,633 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.67575,
    "latitude": 45.5346
  },
  {
    "id": "WO-ELEC-2036",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Needs assignment",
    "district": "West",
    "sla": "4 hr 45 min",
    "impact": "80 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.8074,
    "latitude": 45.53625
  },
  {
    "id": "WO-ELEC-2037",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "High",
    "status": "Queued",
    "district": "North",
    "sla": "6 hr",
    "impact": "127 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.69005,
    "latitude": 45.5749
  },
  {
    "id": "WO-ELEC-2038",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Scheduled",
    "district": "Central",
    "sla": "3 days",
    "impact": "174 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.6697,
    "latitude": 45.53955
  },
  {
    "id": "WO-ELEC-2039",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Assigned",
    "district": "West",
    "sla": "73 min remaining",
    "impact": "221 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.80135,
    "latitude": 45.4962
  },
  {
    "id": "WO-ELEC-2040",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Ready to bundle",
    "district": "North",
    "sla": "4 hr 49 min",
    "impact": "268 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.684,
    "latitude": 45.57985
  },
  {
    "id": "WO-ELEC-2041",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "High",
    "status": "Needs assignment",
    "district": "Central",
    "sla": "10 hr",
    "impact": "315 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.66365,
    "latitude": 45.5445
  },
  {
    "id": "WO-ELEC-2042",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Queued",
    "district": "West",
    "sla": "2 days",
    "impact": "362 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.7953,
    "latitude": 45.50115
  },
  {
    "id": "WO-ELEC-2043",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Scheduled",
    "district": "North",
    "sla": "77 min remaining",
    "impact": "409 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.67795,
    "latitude": 45.5848
  },
  {
    "id": "WO-ELEC-2044",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Assigned",
    "district": "Central",
    "sla": "4 hr 53 min",
    "impact": "456 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.6576,
    "latitude": 45.54945
  },
  {
    "id": "WO-ELEC-2045",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Ready to bundle",
    "district": "West",
    "sla": "79 min remaining",
    "impact": "503 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.78925,
    "latitude": 45.5061
  },
  {
    "id": "WO-ELEC-2046",
    "type": "Feeder Branch Outage",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Needs assignment",
    "district": "North",
    "sla": "1 days",
    "impact": "550 customers affected",
    "crew": "Electric crew recommended",
    "assignmentState": "evaluated",
    "skills": [
      "Switching",
      "Outage restoration",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Switching kit"
    ],
    "longitude": -122.6719,
    "latitude": 45.58975
  },
  {
    "id": "WO-ELEC-2047",
    "type": "Transformer Outage",
    "domain": "Electric",
    "priority": "Emergency",
    "status": "Queued",
    "district": "Central",
    "sla": "81 min remaining",
    "impact": "597 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Transformer replacement",
      "Switching",
      "Outage restoration"
    ],
    "equipment": [
      "Bucket truck",
      "Transformer kit"
    ],
    "longitude": -122.70655,
    "latitude": 45.5094
  },
  {
    "id": "WO-ELEC-2048",
    "type": "Electric Pole Replacement",
    "domain": "Electric",
    "priority": "Critical",
    "status": "Scheduled",
    "district": "West",
    "sla": "4 hr 12 min",
    "impact": "644 customers affected",
    "crew": "Pending review",
    "assignmentState": "unevaluated",
    "skills": [
      "Line construction",
      "Traffic control",
      "Bucket truck"
    ],
    "equipment": [
      "Bucket truck",
      "Pole trailer"
    ],
    "longitude": -122.7832,
    "latitude": 45.51105
  },
  {
    "id": "WO-ELEC-2049",
    "type": "Underground Cable Fault",
    "domain": "Electric",
    "priority": "High",
    "status": "Assigned",
    "district": "North",
    "sla": "6 hr",
    "impact": "691 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Cable fault locating",
      "Underground electric",
      "Switching"
    ],
    "equipment": [
      "Fault locator",
      "Cable repair trailer"
    ],
    "longitude": -122.66585,
    "latitude": 45.5947
  },
  {
    "id": "WO-ELEC-2050",
    "type": "Vegetation Clearance",
    "domain": "Electric",
    "priority": "Routine",
    "status": "Ready to bundle",
    "district": "Central",
    "sla": "5 days",
    "impact": "738 customers affected",
    "crew": "Electric assigned crew",
    "assignmentState": "assigned",
    "skills": [
      "Vegetation clearance",
      "Line patrol"
    ],
    "equipment": [
      "Forestry truck",
      "Chipper"
    ],
    "longitude": -122.7005,
    "latitude": 45.51435
  }
] as const;

export const generatedCrews = [
  {
    "name": "Gas Emergency Response - Andre Lewis",
    "fit": 97,
    "eta": "14 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Emergency",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "Low",
    "hourly": "$138/hr",
    "effectiveCost": "$1,450",
    "longitude": -122.6705,
    "latitude": 45.5818,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Emergency Response - Maya Thompson",
    "fit": 92,
    "eta": "18 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Emergency",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Staged",
    "overtime": "Medium",
    "hourly": "$141/hr",
    "effectiveCost": "$1,635",
    "longitude": -122.702,
    "latitude": 45.5446,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Emergency Response - Luis Rivera",
    "fit": 87,
    "eta": "22 min",
    "district": "West",
    "status": "Available",
    "crewType": "Gas Emergency",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in West district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Transfer required",
    "overtime": "High",
    "hourly": "$144/hr",
    "effectiveCost": "$1,820",
    "longitude": -122.7805,
    "latitude": 45.5044,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Emergency Response - Priya Shah",
    "fit": 82,
    "eta": "26 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Emergency",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Limited",
    "overtime": "Low",
    "hourly": "$147/hr",
    "effectiveCost": "$2,005",
    "longitude": -122.636,
    "latitude": 45.5862,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Emergency Response - Ethan Brooks",
    "fit": 77,
    "eta": "30 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Emergency",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "Medium",
    "hourly": "$150/hr",
    "effectiveCost": "$2,190",
    "longitude": -122.6735,
    "latitude": 45.54,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Construction - Grace Morgan",
    "fit": 72,
    "eta": "34 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Gas Construction",
    "vehicleIcon": "truck",
    "currentAssignment": "Active gas field order",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Staged",
    "overtime": "High",
    "hourly": "$153/hr",
    "effectiveCost": "$2,375",
    "longitude": -122.66,
    "latitude": 45.4818,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Gas Construction - Jordan Kim",
    "fit": 67,
    "eta": "38 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Construction",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Transfer required",
    "overtime": "Low",
    "hourly": "$156/hr",
    "effectiveCost": "$2,560",
    "longitude": -122.6595,
    "latitude": 45.5906,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Construction - Sofia Martinez",
    "fit": 96,
    "eta": "42 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Construction",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Limited",
    "overtime": "Medium",
    "hourly": "$159/hr",
    "effectiveCost": "$2,745",
    "longitude": -122.691,
    "latitude": 45.5134,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Construction - Noah Patel",
    "fit": 91,
    "eta": "46 min",
    "district": "West",
    "status": "Off",
    "crewType": "Gas Construction",
    "vehicleIcon": "truck",
    "currentAssignment": "Off shift",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "High",
    "hourly": "$162/hr",
    "effectiveCost": "$2,930",
    "longitude": -122.7695,
    "latitude": 45.5132,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Off"
    ]
  },
  {
    "name": "Gas Construction - Harper Nguyen",
    "fit": 86,
    "eta": "50 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Construction",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Staged",
    "overtime": "Low",
    "hourly": "$165/hr",
    "effectiveCost": "$3,115",
    "longitude": -122.675,
    "latitude": 45.595,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Regulator Maintenance - Camila Reed",
    "fit": 81,
    "eta": "54 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Maintenance",
    "vehicleIcon": "van",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Transfer required",
    "overtime": "Medium",
    "hourly": "$168/hr",
    "effectiveCost": "$3,300",
    "longitude": -122.6625,
    "latitude": 45.5088,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Regulator Maintenance - Marcus Johnson",
    "fit": 76,
    "eta": "58 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Gas Maintenance",
    "vehicleIcon": "van",
    "currentAssignment": "Active gas field order",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Limited",
    "overtime": "High",
    "hourly": "$171/hr",
    "effectiveCost": "$3,485",
    "longitude": -122.649,
    "latitude": 45.4906,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Gas Regulator Maintenance - Olivia Chen",
    "fit": 71,
    "eta": "62 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Maintenance",
    "vehicleIcon": "van",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "Low",
    "hourly": "$174/hr",
    "effectiveCost": "$3,670",
    "longitude": -122.6985,
    "latitude": 45.5994,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Regulator Maintenance - Darius Walker",
    "fit": 66,
    "eta": "66 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Maintenance",
    "vehicleIcon": "van",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Staged",
    "overtime": "Medium",
    "hourly": "$177/hr",
    "effectiveCost": "$3,855",
    "longitude": -122.68,
    "latitude": 45.5222,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Regulator Maintenance - Nina Patel",
    "fit": 95,
    "eta": "70 min",
    "district": "West",
    "status": "Available",
    "crewType": "Gas Maintenance",
    "vehicleIcon": "van",
    "currentAssignment": "Available in West district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Transfer required",
    "overtime": "High",
    "hourly": "$180/hr",
    "effectiveCost": "$4,040",
    "longitude": -122.7585,
    "latitude": 45.522,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Inspection - Avery Coleman",
    "fit": 90,
    "eta": "74 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Inspection",
    "vehicleIcon": "van",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Limited",
    "overtime": "Low",
    "hourly": "$183/hr",
    "effectiveCost": "$4,225",
    "longitude": -122.664,
    "latitude": 45.5638,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Inspection - Elena Garcia",
    "fit": 85,
    "eta": "78 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Inspection",
    "vehicleIcon": "van",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "Medium",
    "hourly": "$186/hr",
    "effectiveCost": "$4,410",
    "longitude": -122.6515,
    "latitude": 45.5176,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Inspection - Damon Wright",
    "fit": 80,
    "eta": "82 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Gas Inspection",
    "vehicleIcon": "van",
    "currentAssignment": "Active gas field order",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Staged",
    "overtime": "High",
    "hourly": "$189/hr",
    "effectiveCost": "$4,595",
    "longitude": -122.688,
    "latitude": 45.4994,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Gas Inspection - Isabella Ross",
    "fit": 75,
    "eta": "86 min",
    "district": "North",
    "status": "Available",
    "crewType": "Gas Inspection",
    "vehicleIcon": "van",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Transfer required",
    "overtime": "Low",
    "hourly": "$192/hr",
    "effectiveCost": "$4,780",
    "longitude": -122.6875,
    "latitude": 45.5682,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Gas Inspection - Mateo Clark",
    "fit": 70,
    "eta": "90 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Gas Inspection",
    "vehicleIcon": "van",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Gas emergency",
      "Atmospheric testing",
      "Pressure regulation",
      "Traffic control"
    ],
    "equipment": "Limited",
    "overtime": "Medium",
    "hourly": "$195/hr",
    "effectiveCost": "$4,965",
    "longitude": -122.669,
    "latitude": 45.531,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Electric Trouble - Riley Adams",
    "fit": 65,
    "eta": "94 min",
    "district": "West",
    "status": "Available",
    "crewType": "Electric Trouble",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in West district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Ready",
    "overtime": "High",
    "hourly": "$226/hr",
    "effectiveCost": "$5,150",
    "longitude": -122.7975,
    "latitude": 45.5308,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Electric Trouble - Kai Bennett",
    "fit": 94,
    "eta": "98 min",
    "district": "North",
    "status": "Available",
    "crewType": "Electric Trouble",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Staged",
    "overtime": "Low",
    "hourly": "$230/hr",
    "effectiveCost": "$5,335",
    "longitude": -122.653,
    "latitude": 45.5726,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Electric Trouble - Tessa Hall",
    "fit": 89,
    "eta": "102 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Electric Trouble",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Transfer required",
    "overtime": "Medium",
    "hourly": "$234/hr",
    "effectiveCost": "$5,520",
    "longitude": -122.6405,
    "latitude": 45.5264,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Electric Trouble - Owen Foster",
    "fit": 84,
    "eta": "106 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Electric Trouble",
    "vehicleIcon": "bucket",
    "currentAssignment": "Active electric field order",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Limited",
    "overtime": "High",
    "hourly": "$238/hr",
    "effectiveCost": "$5,705",
    "longitude": -122.677,
    "latitude": 45.5082,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Electric Trouble - Leah Simmons",
    "fit": 79,
    "eta": "110 min",
    "district": "North",
    "status": "Available",
    "crewType": "Electric Trouble",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Ready",
    "overtime": "Low",
    "hourly": "$242/hr",
    "effectiveCost": "$5,890",
    "longitude": -122.6765,
    "latitude": 45.577,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Underground Electric - Caleb Price",
    "fit": 74,
    "eta": "114 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Underground Electric",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Staged",
    "overtime": "Medium",
    "hourly": "$246/hr",
    "effectiveCost": "$6,075",
    "longitude": -122.708,
    "latitude": 45.5398,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Underground Electric - Zara Mitchell",
    "fit": 69,
    "eta": "118 min",
    "district": "West",
    "status": "Off",
    "crewType": "Underground Electric",
    "vehicleIcon": "truck",
    "currentAssignment": "Off shift",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Transfer required",
    "overtime": "High",
    "hourly": "$250/hr",
    "effectiveCost": "$6,260",
    "longitude": -122.7865,
    "latitude": 45.4996,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Off"
    ]
  },
  {
    "name": "Underground Electric - Miles Turner",
    "fit": 64,
    "eta": "122 min",
    "district": "North",
    "status": "Available",
    "crewType": "Underground Electric",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Limited",
    "overtime": "Low",
    "hourly": "$254/hr",
    "effectiveCost": "$6,445",
    "longitude": -122.642,
    "latitude": 45.5814,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Underground Electric - Amara Scott",
    "fit": 93,
    "eta": "126 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Underground Electric",
    "vehicleIcon": "truck",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Ready",
    "overtime": "Medium",
    "hourly": "$258/hr",
    "effectiveCost": "$6,630",
    "longitude": -122.6795,
    "latitude": 45.5352,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Underground Electric - Jules Carter",
    "fit": 88,
    "eta": "130 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Underground Electric",
    "vehicleIcon": "truck",
    "currentAssignment": "Active electric field order",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Staged",
    "overtime": "High",
    "hourly": "$262/hr",
    "effectiveCost": "$6,815",
    "longitude": -122.666,
    "latitude": 45.477,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Line Construction - Rafael Ortiz",
    "fit": 83,
    "eta": "134 min",
    "district": "North",
    "status": "Available",
    "crewType": "Line Patrol",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Transfer required",
    "overtime": "Low",
    "hourly": "$266/hr",
    "effectiveCost": "$7,000",
    "longitude": -122.6655,
    "latitude": 45.5858,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Line Construction - Mina Park",
    "fit": 78,
    "eta": "138 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Line Patrol",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Limited",
    "overtime": "Medium",
    "hourly": "$270/hr",
    "effectiveCost": "$7,185",
    "longitude": -122.697,
    "latitude": 45.5486,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Line Construction - Theo Russell",
    "fit": 73,
    "eta": "142 min",
    "district": "West",
    "status": "Available",
    "crewType": "Line Patrol",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in West district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Ready",
    "overtime": "High",
    "hourly": "$274/hr",
    "effectiveCost": "$7,370",
    "longitude": -122.7755,
    "latitude": 45.5084,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Line Construction - Layla Hughes",
    "fit": 68,
    "eta": "146 min",
    "district": "North",
    "status": "Available",
    "crewType": "Line Patrol",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Staged",
    "overtime": "Low",
    "hourly": "$278/hr",
    "effectiveCost": "$7,555",
    "longitude": -122.631,
    "latitude": 45.5902,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Line Construction - Grant Bailey",
    "fit": 97,
    "eta": "150 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Line Patrol",
    "vehicleIcon": "bucket",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Transfer required",
    "overtime": "Medium",
    "hourly": "$282/hr",
    "effectiveCost": "$7,740",
    "longitude": -122.6685,
    "latitude": 45.504,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Vegetation Line Clearance - Iris Cooper",
    "fit": 92,
    "eta": "154 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Vegetation",
    "vehicleIcon": "patrol",
    "currentAssignment": "Active electric field order",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Limited",
    "overtime": "High",
    "hourly": "$286/hr",
    "effectiveCost": "$7,925",
    "longitude": -122.655,
    "latitude": 45.4858,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Vegetation Line Clearance - Cole Jenkins",
    "fit": 87,
    "eta": "158 min",
    "district": "North",
    "status": "Available",
    "crewType": "Vegetation",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Ready",
    "overtime": "Low",
    "hourly": "$290/hr",
    "effectiveCost": "$8,110",
    "longitude": -122.7045,
    "latitude": 45.5946,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Vegetation Line Clearance - Nora Flores",
    "fit": 82,
    "eta": "162 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Vegetation",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Staged",
    "overtime": "Medium",
    "hourly": "$294/hr",
    "effectiveCost": "$8,295",
    "longitude": -122.686,
    "latitude": 45.5174,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Vegetation Line Clearance - Simon Ward",
    "fit": 77,
    "eta": "166 min",
    "district": "West",
    "status": "Available",
    "crewType": "Vegetation",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in West district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Transfer required",
    "overtime": "High",
    "hourly": "$298/hr",
    "effectiveCost": "$8,480",
    "longitude": -122.7645,
    "latitude": 45.5172,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Vegetation Line Clearance - Vivian Kelly",
    "fit": 72,
    "eta": "170 min",
    "district": "North",
    "status": "Available",
    "crewType": "Vegetation",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Switching",
      "Outage restoration",
      "Bucket truck",
      "Line patrol"
    ],
    "equipment": "Limited",
    "overtime": "Low",
    "hourly": "$302/hr",
    "effectiveCost": "$8,665",
    "longitude": -122.67,
    "latitude": 45.599,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Damage Assessment - Micah Bell",
    "fit": 67,
    "eta": "174 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Inspection",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Damage assessment",
      "Field inspection",
      "Customer restoration",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "Medium",
    "hourly": "$202/hr",
    "effectiveCost": "$8,850",
    "longitude": -122.6575,
    "latitude": 45.5128,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Damage Assessment - Ari Brooks",
    "fit": 96,
    "eta": "178 min",
    "district": "South",
    "status": "Assigned",
    "crewType": "Inspection",
    "vehicleIcon": "patrol",
    "currentAssignment": "Active shared field order",
    "certifications": [
      "Damage assessment",
      "Field inspection",
      "Customer restoration",
      "Traffic control"
    ],
    "equipment": "Staged",
    "overtime": "High",
    "hourly": "$204/hr",
    "effectiveCost": "$9,035",
    "longitude": -122.644,
    "latitude": 45.4946,
    "strengths": [
      "Qualified craft lead",
      "South district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Assigned"
    ]
  },
  {
    "name": "Damage Assessment - June Parker",
    "fit": 91,
    "eta": "182 min",
    "district": "North",
    "status": "Available",
    "crewType": "Inspection",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in North district",
    "certifications": [
      "Damage assessment",
      "Field inspection",
      "Customer restoration",
      "Traffic control"
    ],
    "equipment": "Transfer required",
    "overtime": "Low",
    "hourly": "$206/hr",
    "effectiveCost": "$9,220",
    "longitude": -122.6935,
    "latitude": 45.5634,
    "strengths": [
      "Qualified craft lead",
      "North district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Damage Assessment - Reid Murphy",
    "fit": 86,
    "eta": "186 min",
    "district": "Central",
    "status": "Available",
    "crewType": "Inspection",
    "vehicleIcon": "patrol",
    "currentAssignment": "Available in Central district",
    "certifications": [
      "Damage assessment",
      "Field inspection",
      "Customer restoration",
      "Traffic control"
    ],
    "equipment": "Limited",
    "overtime": "Medium",
    "hourly": "$208/hr",
    "effectiveCost": "$9,405",
    "longitude": -122.675,
    "latitude": 45.5262,
    "strengths": [
      "Qualified craft lead",
      "Central district coverage",
      "Current equipment profile available"
    ],
    "penalties": []
  },
  {
    "name": "Damage Assessment - Naomi Sanders",
    "fit": 81,
    "eta": "190 min",
    "district": "West",
    "status": "Off",
    "crewType": "Inspection",
    "vehicleIcon": "patrol",
    "currentAssignment": "Off shift",
    "certifications": [
      "Damage assessment",
      "Field inspection",
      "Customer restoration",
      "Traffic control"
    ],
    "equipment": "Ready",
    "overtime": "High",
    "hourly": "$210/hr",
    "effectiveCost": "$9,590",
    "longitude": -122.8035,
    "latitude": 45.526,
    "strengths": [
      "Qualified craft lead",
      "West district coverage",
      "Current equipment profile available"
    ],
    "penalties": [
      "Crew status is Off"
    ]
  }
] as const;
